language: node_js
node_js:
- '6'
- '8'
- '9'
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm --version
- node_modules/.bin/builder run check-ci
- if [ "${TRAVIS_EVENT_TYPE}" = "push" ]; then npm run chromatic-test; fi
- npm prune --production
- node_modules/.bin/builder run build

env:
  global:
    # CHROMATIC_APP_CODE
    secure: VhAuOC061VVV0wGxzXRK1uIGWv0fxzIvoEJHYKBnaoyOsZKUXUzBLVyHRu5Ipb1a2EHYDu0Xd7gNdA4UZ3HazuKNCDyZyJBc7fudlD6U1ZPKnSa0CezUS6U/2eh8WHMocxph1Ut7m73BSAMnSfxUJneaXUDjGOeWhtntiq7rljYX1Au4vnUfaW1R5tYlP/3MuZ+0F6BcejEIgYCJF2m41rhxFSAMTDdqQGMcYsQ9NkEqjJf7K48t3hv+uCFR+d6bDG0yqrgPtJgaNr0iniiRejSd1+/BM1Y/uSPYVrSexjWtmWG43WKlsQv0NCyeCiothbwDOVOq6L/HPpLXR2vnyIIxZwOrGsSnhGQyiJWvByuGPUPvzEYbrxBSL6SYeKJ+oBWLpCFcT8gvODw3Aak3O02cE2xhNGlZvlPyNoNT3XDhmUAZWBZevDTxmndp8DKQNre3LpkukZxEA83uCGgW1RcuoTVcdin+Fc6GH41oSoDdUA/Ahxvak9Jsyo3nUDJOj2NBNxEhm2JxabneO+/QR3y6Gov1SIgAbaxWsanyQHsnkhMsKXLhK4dD6a8RcWVMuqTZxviU0upCEs3iB6mpxKK2hZ5o5gUOiwH5/pljnoyCs5rfmawfI7TMoic6G831yNCu5oUB4aY5T33ZOZVCzdUdlokxU9g1FvarnU2mQxM=
