language: node_js
node_js:
- '6'
- '8'
- '9'
sudo: false
branches:
  only:
    - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm --version
- node_modules/.bin/builder run check-ci
- if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm run chromatic-test; fi
- npm prune --production
- node_modules/.bin/builder run build

env:
  global:
    # CHROMATIC_APP_CODE
    secure: PxMDiElEAalSa8cxvsbYP9eegmgq5V73K9RMVrPGAqHBAK92z4P3+GpU4K1s6JhZLK+qaBsp6eA/tzE/TG2zzQgxXNFTgB9CIzqMk92eMIjK+U0kABru4gUP21v6t3vt2m6V8+RIlXjfL5I29WHqLxp6s7ValmN+CrutMSYYQaNS3yZ6RgvxBiMlvRqELuiCtM49YDy5k0W1Cn1CP8H1DMUk8yrl/fzc44Qm4piSoHLREnQVY/HOz7BWXmD28sZkGtt6Uf3gHFsTBaT+AANcwTB5afRKa351TWaJbAFSGcEKW9oCCo8yR0CTcuLRZLIvkBkMHgceNb6o9oOkMyqDwEZvJU4sGQB+F/rXMxRT+YMU3QFsWG6yZ8M0CSJAwvch5zgcOCKaNyeq1VMmr7YaFzJ9Ux0TT+QPM74DMF3MJPB3O6L+0hcSNNZgcFrNfoT4t8b95PTo4GFw80v6/3rJjRTwfSHO1YRes9+dIydlavgdkd7qInr+t1lfTECjjBrcvh/hqNMtLJyK5fsaMA7Boj0GtjW7v8nOdEvri9NCd02ur9nNGaVW7HCFzEQ/Jf7kqjWndfGyv60+RjP/VU8wma6p7lOMrSQC6fxRhvWycyNzZ5pzRzwXtTy34jvvuhvgNgNya7ArnT+r9vCajikY4tk31XrOCxB7VCyQv8Qz+FA=
