language: node_js
node_js:
- '6'
- '8'
- '9'
sudo: false
branches:
  only:
    - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- yarn --version
- yarn nps check.ci
