language: node_js

node_js:
  - "4"
  - "6"

# Use container-based Travis infrastructure.
sudo: false

branches:
  only:
    - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Install npmv3 because of postinstall bugs in npmv2:
  # See https://github.com/FormidableLabs/victory/issues/98
  - npm install -g npm@3

script:
  - "echo ${TRAVIS_EVENT_TYPE}"
  - npm --version
  - node_modules/.bin/builder run check-ci
  # Only run chromatic suite on node 6
  - if [ "${TRAVIS_NODE_VERSION}" = "6" ]; then npm run chromatic-test; fi
  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - node_modules/.bin/builder run build
env:
  global:
    # CHROMATIC_APP_CODE
    secure: PWpQ9XPMxuKsUodRZdr0dBpaT2tqiWSeF+hO1si7owhUsMmsNWyX6Y97u3i6ahutMMzUjz3gv0E8QwMjcwFHXfmkqHi8d9XggYGG9VkU9yIeaixpOH/cQXrjJf2s2TmtiNS5gB0moeR2QDmur0MQcTssn5CD4ScpbZK+TzCWX9bh5uZCin9ej2J3BOPbMVbk0d4bTGJVAVSbxVK1onshPATYimLXe/gO9YYL5EVzN6Odb/IEjKMVjUOzocoU0ZbG3RGES93I0fNtCxix5uHESBJte8Hh4xhVbKw34A09GznPYM91TIde6VxS3BJ+E/kG+1a0FUmH2PVi2eOryO3MKOG44FZewVNZolQTtIvWxn/Tv2FMKTLyap2/4yA338ExOHNroBnmiMxJkH9kbRVxv7BDVciOvLm/2WzenQxzCqan+/uLj3FHeTDwoqWJfSqzv0MA8rNNttMSUBeHpjcoF15i7Q1rTozdrUjcmEuDh40eV09p+u1woMCES+95mIpkVqPltYTEmH11zQRLwIp65T53FPbo93/1Vn9rGv5zrIPCO60ZTC3qIUMcZ8YQA5K6lGt7axWDUlK6o7P9sWNGagk4m2fj0bsexQ7mKohHnzKtxsG6Q/kQPYYePXw+mzbHzvPPLcRWdUND/hFRtF5fjMPClYTT0rIy5y502DTl+js=
