language: node_js

node_js:
  - "6"
  - "8"
  - "9"

# Use container-based Travis infrastructure.
sudo: false

# TODO(957): Re-enable `pull_request` only builds.
# https://github.com/FormidableLabs/victory/issues/957
# branches:
#   only:
#     - master

before_install:
  # GUI for real browsers.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm --version
  - node_modules/.bin/builder run check-ci
  # Only run on push events.
  - if [ "${TRAVIS_EVENT_TYPE}" = "push" ]; then npm run chromatic-test; fi
  # Prune deps to just production and ensure we can still build
  - npm prune --production
  - node_modules/.bin/builder run build
