language: node_js
node_js:
- '6'
- '8'
- '9'
sudo: false
branches:
  only:
    - master
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- npm --version
- node_modules/.bin/builder run check-ci
- npm prune --production
- node_modules/.bin/builder run build
